IBDbWebApplication/Models/AdminModels/GenreModels/GenreViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels;

public class GenreViewModel
{
    [Key]
    public int Id { get; set; }
    
    [DisplayName("Name")]
    [Required(ErrorMessage = "A name is required")]
    [StringLength(25, ErrorMessage = "Name must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z ,&]+$", ErrorMessage = "Name can only contain letters, spaces, commas, and ampersands.")]
    public string Name { get; set; }

    public IEnumerable<GenreModel> GenreModels { get; set; }

    public GenreViewModel(IEnumerable<GenreModel> genreModels) => GenreModels = genreModels;

    public GenreViewModel() { }
}

IBDbWebApplication/Models/GenreModels/GenreViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels;

public class GenreViewModel
{
    [Key]
    public int Id { get; set; }
    
    [DisplayName("Name")]
    [Required(ErrorMessage = "A name is required")]
    [StringLength(25, ErrorMessage = "Name must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z ,&]+$", ErrorMessage = "Name can only contain letters, spaces, commas, and ampersands.")]
    public string Name { get; set; }

    public IEnumerable<GenreModel> GenreModels { get; set; } = new List<GenreModel>();

    public GenreViewModel(IEnumerable<GenreModel> genreModels) => GenreModels = genreModels;

    public GenreViewModel() { }
}

IBDbWebApplication/Controllers/GenreController.cs
using System.Text.RegularExpressions;
using Business.Container;
using Data.MsSQL;
using IBDbWebApplication.Models.AdminModels;
using IBDbWebApplication.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace IBDbWebApplication.Controllers;

public class GenreController : Controller
{
    private readonly GenreContainer _genreContainer = new(new GenreData());
    
    [HttpGet]
    public IActionResult Index()
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");

        return View(GetGenreViewModel());
    }
    
    private GenreViewModel GetGenreViewModel()
    {
        return new(
            GetGenreModels()
        );
    }
    
    [HttpPost]
    public IActionResult AddGenre(GenreViewModel genreViewModel)
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        if (!ModelState.IsValid)
        {
            return View(nameof(Index), GetGenreViewModel());
        }

        try
        {
            _genreContainer.Add(new((byte?)genreViewModel.Id, genreViewModel.Name));
        }
        catch (AggregateException aggregateException)
        {
            foreach (Exception innerException in aggregateException.InnerExceptions)
            {
                ModelState.AddModelError($"{Regex.Replace(innerException.GetType().GetProperty("Type").GetValue(innerException) as string, @"\s", "")}", innerException.Message);
            }
            return View(nameof(Index), GetGenreViewModel());
        }

        
        return RedirectToAction(nameof(Index));
    }
    
    private IEnumerable<GenreModel> GetGenreModels()
    {
        return _genreContainer.GetAll().Select(genre => new GenreModel(genre.Id, genre.Name));
    }
}

IBDbWebApplication/Views/Genre/Index.cshtml
@using IBDbWebApplication.Models.Entity
@model IBDbWebApplication.Models.AdminModels.GenreViewModel
@{
    ViewData["Title"] = "IBDb | Admin genre";
    string[] validationErrors = TempData["ValidationErrors"] as string[];}

<div class="MainContainer">
    <div class="hero">
        <h1>Manage genres</h1>
    </div>
    <section>
        <ul class="operations">
            <li>
                <div class="operation-button" onclick="ShowDialog()">
                    <p>➕</p>
                    <h2>Create</h2>
                </div>
                <dialog id="AddForm">
                    <div class="modal-content">
                    @using (@Html.BeginForm("AddGenre", "Genre", FormMethod.Post))
                    {
                        <button type="button" class="btn-close" onclick="CloseDialog()">X</button>
                        <fieldset>
                            <legend>Add a Genre</legend>
                            <div class="form-group">
                                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                                @Html.LabelFor(genreViewModel => genreViewModel.Name, "Name")
                                @Html.TextBoxFor(model => model.Name, new {@placeholder = "Horror"})
                            </div>
                        </fieldset>
                        <button id="ButtonMelding" type="submit">Add Genre</button>
                    }
                    </div>
                </dialog>
            </li>
        </ul>
    </section>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach (GenreModel genre in Model.GenreModels)
        {
            <tr>
                <td>@genre.Id</td>
                <td>@genre.Name</td>
            </tr>
        }
        </tbody>
    </table>
</div>