IBDbWebApplication/Models/AdminModels/SettingModels/SettingViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels.SettingModels;

public class SettingViewModel
{
    public byte? Id { get; }
    
    [DisplayName("Description")]
    [Required(ErrorMessage = "Description is required")]
    [StringLength(25, ErrorMessage = "Description must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z ,&]+$", ErrorMessage = "Description can only contain letters, spaces, commas, and ampersands.")]
    public string Description { get; set; }
    
    public IEnumerable<SettingModel> SettingModels { get; set; }
    
    public SettingViewModel(IEnumerable<SettingModel> settingModels) => SettingModels = settingModels;

    public SettingViewModel() { }
}

IBDbWebApplication/Models/SettingModels/SettingViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels.SettingModels;

public class SettingViewModel
{
    public byte? Id { get; }
    
    [DisplayName("Description")]
    [Required(ErrorMessage = "Description is required")]
    [StringLength(25, ErrorMessage = "Description must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z0-9 ,&]+$", ErrorMessage = "Description can only contain letters, spaces, commas, and ampersands.")]
    public string Description { get; set; }
    
    public IEnumerable<SettingModel> SettingModels { get; set; } = new List<SettingModel>();
    
    public SettingViewModel(IEnumerable<SettingModel> settingModels) => SettingModels = settingModels;

    public SettingViewModel() { }
}

IBDbWebApplication/Controllers/SettingController.cs
using System.Text.RegularExpressions;
using Business.Container;
using Data.MsSQL;
using IBDbWebApplication.Models.AdminModels.SettingModels;
using IBDbWebApplication.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace IBDbWebApplication.Controllers;

public class SettingController : Controller
{
    private readonly SettingContainer _settingContainer = new(new SettingData());
    
    [HttpGet]
    public IActionResult Index()
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        return View(GetSettingViewModel());
    }
    
    private SettingViewModel GetSettingViewModel()
    {
        return new(
            GetSettingModels()
        );
    }
    
    [HttpPost]
    public IActionResult AddSetting(SettingViewModel settingViewModel)
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        if (!ModelState.IsValid)
        {
            return View(nameof(Index), GetSettingViewModel());
        }

        try
        {
            _settingContainer.Add(new(settingViewModel.Id, settingViewModel.Description));
        }
        catch (AggregateException aggregateException)
        {
            foreach (Exception innerException in aggregateException.InnerExceptions)
            {
                ModelState.AddModelError($"{Regex.Replace(innerException.GetType().GetProperty("Type").GetValue(innerException) as string, @"\s", "")}", innerException.Message);
            }
            return View(nameof(Index), GetSettingViewModel());
        }
        
        return RedirectToAction(nameof(Index));
    }
    
    private IEnumerable<SettingModel> GetSettingModels()
    {
        return _settingContainer.GetAll().Select(setting => new SettingModel(setting.Id, setting.Description));
    }
}

IBDbWebApplication/Views/Admin/Setting/Index.cshtml
@using IBDbWebApplication.Models.Entity
@model IBDbWebApplication.Models.AdminModels.SettingModels.SettingViewModel
@{
    ViewData["Title"] = "IBDb | Admin setting";
}

<div class="MainContainer">
    <div class="hero">
        <h1>Manage settings</h1>
    </div>
    <section>
        <ul class="operations">
            <li>
                <div class="operation-button" onclick="ShowDialog()">
                    <p>➕</p>
                    <h2>Create</h2>
                </div>
                <dialog id="AddForm">
                    <div class="modal-content">
                        @using (@Html.BeginForm("AddSetting", "Setting", FormMethod.Post))
                        {
                            <button type="button" class="btn-close" onclick="CloseDialog()">X</button>
                            <fieldset>
                                <legend>Add a Setting</legend>
                                <div class="form-group">
                                    @Html.LabelFor(settingViewModel => settingViewModel.Description, "Description")
                                    @Html.TextBoxFor(model => model.Description, new { @placeholder = "Atlantis" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </fieldset>
                            <button id="ButtonMelding" type="submit">Add Setting</button>
                        }
                    </div>
                </dialog>
            </li>
        </ul>
    </section>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach (SettingModel setting in Model.SettingModels)
        {
            <tr>
                <td>@setting.Id</td>
                <td>@setting.Description</td>
            </tr>
        }
        </tbody>
    </table>
</div>