IBDbWebApplication/Models/PublisherModels/PublisherViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels.PublisherModels;

public class PublisherViewModel
{
    [Key]
    public long? Id { get; set; }
    
    [DisplayName("Name")]
    [Required(ErrorMessage = "Name is required")]
    [StringLength(50, ErrorMessage = "Name must be between 1 and 50 characters", MinimumLength = 1 )]
    [RegularExpression(@"^[a-zA-Z &]+$", ErrorMessage = "Name must only contain letters, spaces, and ampersand.")]
    public string Name { get; set; }
    
    [DisplayName("Founding date")]
    [Required(ErrorMessage = "Founding date is required")]
    [DataType(DataType.Date)]
    public DateTime? FoundingDate { get; set; }
    
    [DisplayName("Description")]
    [Required(ErrorMessage = "Description is required")]
    [StringLength(1000, ErrorMessage = "Description must be between 10 and 1000 characters", MinimumLength = 10 )]
    public string Description { get; set; }

    public IEnumerable<PublisherModel> PublisherModels { get; set; } = new List<PublisherModel>();

    public PublisherViewModel(IEnumerable<PublisherModel> publisherModels) => PublisherModels = publisherModels;

    public PublisherViewModel() { }
}

IBDbWebApplication/Controllers/PublisherController.cs
using System.Text.RegularExpressions;
using Business.Container;
using Data.MsSQL;
using IBDbWebApplication.Models.AdminModels.PublisherModels;
using IBDbWebApplication.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace IBDbWebApplication.Controllers;

public class PublisherController : Controller
{
    private readonly PublisherContainer _publisherContainer = new(new PublisherData());
    
    [HttpGet]
    public IActionResult Index()
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        return View(GetPublisherViewModel());
    }
    
    private PublisherViewModel GetPublisherViewModel()
    {
        return new(
            GetPublisherModels()
        );
    }
    
    [HttpPost]
    public IActionResult AddPublisher(PublisherViewModel publisherViewModel)
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        if (!ModelState.IsValid)
        {
            return View(nameof(Index), GetPublisherViewModel());
        }

        try
        {
            _publisherContainer.Add(new(
                publisherViewModel.Id, 
                publisherViewModel.Name, 
                DateOnly.FromDateTime(publisherViewModel.FoundingDate.Value), 
                publisherViewModel.Description)
            );
        }
        catch (AggregateException aggregateException)
        {
            foreach (Exception innerException in aggregateException.InnerExceptions)
            {
                ModelState.AddModelError($"{Regex.Replace(innerException.GetType().GetProperty("Type").GetValue(innerException) as string, @"\s", "")}", innerException.Message);
            }
            return View(nameof(Index), GetPublisherViewModel());
        }
        
        
        return RedirectToAction(nameof(Index));
    }
    
    private IEnumerable<PublisherModel> GetPublisherModels()
    {
        return _publisherContainer.GetAll().Select(publisher => new PublisherModel(publisher.Id, publisher.Name, publisher.FoundingDate, publisher.Description));
    }
}

IBDbWebApplication/Views/Admin/Publisher/Index.cshtml
@using IBDbWebApplication.Models.Entity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IBDbWebApplication.Models.AdminModels.PublisherModels.PublisherViewModel
@{
    ViewData["Title"] = "IBDb | Admin publisher";
}

<div class="MainContainer">
    <div class="hero">
        <h1>Manage publishers</h1>
    </div>
    <section>
        <ul class="operations">
            <li>
                <div class="operation-button" onclick="ShowDialog()">
                    <p>➕</p>
                    <h2>Create</h2>
                </div>
                <dialog id="AddForm">
                    <div class="modal-content">
                    @using (@Html.BeginForm("AddPublisher", "Publisher", FormMethod.Post))
                    {
                        <button type="button" class="btn-close" onclick="CloseDialog()">X</button>
                        <fieldset>
                            <legend>Add a Publisher</legend>
                            <div class="form-group">
                                @Html.LabelFor(publisherViewModel => publisherViewModel.Name, "Name")
                                @Html.TextBoxFor(model => model.Name, new { @placeholder = "J.K. Rowling" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(publisherViewModel => publisherViewModel.FoundingDate, "FoundingDate")
                                <input asp-for="FoundingDate"/>
                                @Html.ValidationMessageFor(model => model.FoundingDate, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(publisherViewModel => publisherViewModel.Description, "Description")
                                @Html.TextBoxFor(model => model.Description, new { @placeholder = "Queen of wizardry" })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </fieldset>
                        <button id="ButtonMelding" type="submit">Add Publisher</button>
                    }
                    </div>
                </dialog>
            </li>
        </ul>
    </section>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Founding date</th>
            <th>Description</th>
        </tr>
        </thead>
        <tbody>
        @foreach (PublisherModel publisher in Model.PublisherModels)
        {
            <tr>
                <td>@publisher.Id</td>
                <td>@publisher.Name</td>
                <td>@publisher.FoundingDate</td>
                <td>@publisher.Description</td>
            </tr>
        }
        </tbody>
    </table>
</div>