IBDbWebApplication/Models/AdminModels/ThemeModels/ThemeViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels.ThemeModels;

public class ThemeViewModel
{
    public byte? Id { get; set; }
    
    [DisplayName("Description")]
    [Required(ErrorMessage = "Description is required")]
    [StringLength(25, ErrorMessage = "Description must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z ,&]+$", ErrorMessage = "Description can only contain letters, spaces, commas, and ampersands.")]
    public string Description { get; set; }
    
    public IEnumerable<ThemeModel> ThemeModels { get; set; }
    
    public ThemeViewModel(IEnumerable<ThemeModel> themeModels) => ThemeModels = themeModels;
    
    public ThemeViewModel() { }
}

IBDbWebApplication/Models/ThemeModels/ThemeViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using IBDbWebApplication.Models.Entity;

namespace IBDbWebApplication.Models.AdminModels.ThemeModels;

public class ThemeViewModel
{
    public byte? Id { get; set; }
    
    [DisplayName("Description")]
    [Required(ErrorMessage = "Description is required")]
    [StringLength(25, ErrorMessage = "Description must be between 2 and 25 characters", MinimumLength = 2 )]
    [RegularExpression(@"^[a-zA-Z ,&+-]+$", ErrorMessage = "Description can only contain letters, spaces, commas, plus, minus, and ampersands.")]
    public string Description { get; set; }
    
    public IEnumerable<ThemeModel> ThemeModels { get; set; } = new List<ThemeModel>();
    
    public ThemeViewModel(IEnumerable<ThemeModel> themeModels) => ThemeModels = themeModels;
    
    public ThemeViewModel() { }
}

IBDbWebApplication/Controllers/ThemeController.cs
using System.Text.RegularExpressions;
using Business.Container;
using Data.MsSQL;
using IBDbWebApplication.Models.AdminModels.ThemeModels;
using IBDbWebApplication.Models.Entity;
using Microsoft.AspNetCore.Mvc;

namespace IBDbWebApplication.Controllers;

public class ThemeController : Controller
{
    private readonly ThemeContainer _themeContainer = new(new ThemeData());
    
    [HttpGet]
    public IActionResult Index()
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        return View(GetThemeViewModel());
    }
    
    private ThemeViewModel GetThemeViewModel()
    {
        return new(
            GetThemeModels()
        );
    }

    [HttpPost]
    public IActionResult AddTheme(ThemeViewModel themeViewModel)
    {
        if (HttpContext.Session.GetInt32("IsAdmin") == 0)
            return RedirectToAction("Login", "Account");
        
        if (!ModelState.IsValid)
        {
            return View(nameof(Index), GetThemeViewModel());
        }

        try
        {
            _themeContainer.Add(new(themeViewModel.Id, themeViewModel.Description));
        }
        catch (AggregateException aggregateException)
        {
            foreach (Exception innerException in aggregateException.InnerExceptions)
            {
                ModelState.AddModelError($"{Regex.Replace(innerException.GetType().GetProperty("Type").GetValue(innerException) as string, @"\s", "")}", innerException.Message);
            }
            return View(nameof(Index), GetThemeViewModel());
        }
        
        return RedirectToAction(nameof(Index));
    }
    
    private IEnumerable<ThemeModel> GetThemeModels()
    {
        return _themeContainer.GetAll().Select(theme => new ThemeModel(theme.Id, theme.Description));
    }
}

IBDbWebApplication/Views/Admin/Theme/Index.cshtml
@using IBDbWebApplication.Models.Entity
@model IBDbWebApplication.Models.AdminModels.ThemeModels.ThemeViewModel
@{
    ViewData["Title"] = "IBDb | Admin theme";
}

<div class="MainContainer">
    <div class="hero">
        <h1>Manage themes</h1>
    </div>
    <section>
        <ul class="operations">
            <li>
                <div class="operation-button" onclick="ShowDialog()">
                    <p>➕</p>
                    <h2>Create</h2>
                </div>
                <dialog id="AddForm">   
                    <div class="modal-content">
                        @using (@Html.BeginForm("AddTheme", "Theme", FormMethod.Post))
                        {
                            <button type="button" class="btn-close" onclick="CloseDialog()">X</button>
                            <fieldset>
                                <legend>Add a Theme</legend>
                                <div class="form-group">
                                    @Html.LabelFor(themeViewModel => themeViewModel.Description, "Description")
                                    @Html.TextBoxFor(model => model.Description, new { @placeholder = "LGBTQIA+" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </fieldset>
                            <button id="ButtonMelding" type="submit">Add Theme</button>
                        }
                    </div>
                </dialog>
            </li>
        </ul>
    </section>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        @foreach (ThemeModel themeModel in Model.ThemeModels)
        {
            <tr>
                <td>@themeModel.Id</td>
                <td>@themeModel.Description</td>
            </tr>
        }
        </tbody>
    </table>
</div>